{
 "title": "RPS kratos",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "method", "query": "GET,POST,PUT,DELETE,HEAD" },
   {
    "name": "path",
    "query": {
     "query": "label_values(lite_kratos_http_response_count_total{request_uri!=\"\"}, request_uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(lite_kratos_http_response_count_total[5m])) * on "
    }
   ]
  },
  {
   "title": "RPS Per Module",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lite_kratos_http_response_count_total{job=\"acccess-log-exporter\",method=~\"$method\",request_uri=~\"$path\",status=~\"(200|3..)\"}[5m])) by (method, request_uri, status) ",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lite_kratos_http_response_count_total[10m]))"
    }
   ]
  }
 ]
}